@localhost=localhost:4004/odata/v4/main
@id = 4105a378-05e3-4602-a608-85230486ab75
@customerId = 4105a378-05e3-4602-a608-85230486ab76
@productId = 4105a378-05e3-4602-a608-85230486ab77

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "4105a378-05e3-4602-a608-85230486ab78",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "4105a378-05e3-4602-a608-85230486ab79",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "teste"
}

###

// pegar os TotalAmount maior ou igual a x valor
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json

###

// expandindo os items
GET http://{{localhost}}/SalesOrderHeaders?$expand=items
Content-Type: application/json

###

// expansão dupla
GET http://{{localhost}}/SalesOrderHeaders?$expand=items,customer
Content-Type: application/json

###

// selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Content-Type: application/json