@localhost=localhost:4004/odata/v4/main
@id = 4105a378-05e3-4602-a608-85230486ab75
@customerId = 4105a378-05e3-4602-a608-85230486ab76
@productId1 = 23075302-1d15-4143-9421-c367195527e8
@productId2 = 10194035-b1b6-44ed-9725-4f22cb56a4eb

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "4105a378-05e3-4602-a608-85230486ab78",
            "header_id": "{{id}}",
            "product_id": "{{productId1}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "4105a378-05e3-4602-a608-85230486ab79",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

{
    "modifiedBy": "teste"
}

###

// pegar os TotalAmount maior ou igual a x valor
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

// expandindo os items
GET http://{{localhost}}/SalesOrderHeaders?$expand=items
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

// expansão dupla
GET http://{{localhost}}/SalesOrderHeaders?$expand=items,customer
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

// selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

// descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

// paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=0&$top=5
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

###

// buscando dados com search
GET http://{{localhost}}/SalesOrderHeaders?$search=example.net
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

// funcionalidade de clonar pedidos
// achar um pedido que tenha o customer e items
POST http://{{localhost}}/SalesOrderHeaders(colocar-id)
Content-Type: application/json
Authorization: Basic joaozinho:inicial@12345

{}